production:
  access_key_id: AWS_ACCESS_KEY_ID 
  secret_access_key: AWS_SECRET_ACCESS_KEY
  bucket: S3_BUCKET
  endpoint:
  secure:
  private:
  expires: 
  proxy:

development:
  access_key_id: AWS_ACCESS_KEY_ID 
  secret_access_key: AWS_SECRET_ACCESS_KEY
  bucket: S3_BUCKET
  endpoint:
  secure:
  private:
  expires: 
  proxy: